config/routes.rb
Paypalabels::Application.routes.draw do
  resources :mailings do
    collection do
      post "summary"
    end
  end

  root :to => "mailings#new"

end

app/models/contact.rb
class Contact
  extend FieldFixings

  FIELDS = [:name, :address_1, :address_2,
            :city, :state, :zipcode, :country,
            :value, :item_title, :note,
            :postage_price, :buyer_id]

  attr_reader *FIELDS

  camel_case :name, :address_1, :address_2, :country, :city, :state
  upper_case :zipcode
  floated :postage_price, :value

  def initialize(csv_row)
    FIELDS.each do |field|
      instance_variable_set "@#{field.to_s}", csv_row[field]
    end
  end
end

app/models/mailing.rb
class Mailing
  
  HEADER_DICTIONARY = {
    "Date" => :date,
    "Time" => :time,
    "Time Zone" => :time_zone,
    "Name" => :name, 
    "Type" => :transaction_type,
    "Status" => :transaction_status,
    "Currency" => :currency,
    "Gross" => :value,
    "Fee" => :paypal_fee,
    "Net" => :income,
    "Note" => :note,
    "From Email Address" => :sender,
    "To Email Address" => :recipient,
    "Transaction ID" => :transaction_id,
    "Item Title" => :item_title,
    "Postage and Packing" => :postage_price,
    "Buyer ID" => :buyer_id,
    "Reference Txn ID" => :tax_id,
    "Receipt ID" => :receipt_id,
    "Address Line 1" => :address_1,
    "Address Line 2/District/Neighbourhood" => :address_2,
    "Town/City" => :city,
    "State/Province/Region/County/Territory/Prefecture/Republic" => :state,
    "Postcode" => :zipcode,
    "Country" => :country
    
  }
  
  attr_reader :rows
  attr_reader :headers

  def initialize(body)
    @rows = []
    FasterCSV.parse(body) do |row|
      @rows << row[0..-2].map(&:strip)
    end

    @headers = translate_headers @rows.shift

    @rows.map! do |row|
      row = Hash[*@headers.zip(row).flatten]
    end
  end

  def contacts
    @rows.map {|row| Contact.new row }
  end

  private

  def translate_headers(headers)
    headers.map {|header| HEADER_DICTIONARY[header]}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  def new
  end

  def create
    @contacts = Mailing.new(params[:payments].read).contacts
    if params[:skip].to_i > 0
      params[:skip].to_i.times do
        @contacts.unshift Contact.new({})
      end
    end
  end

  def summary
    @contacts = Mailing.new(params[:payments].read).contacts.group_by(&:item_title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mailing_helper.rb
module MailingHelper
  def html_class_for(contact)
    returning [cycle("odd", "even")] do |classes|
      classes << "noted" if contact.note.to_s.strip.present?
      classes << "special-postage" unless contact.postage_price.to_f == 0.00
    end.join(' ')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paypalabels</title>
  <%= stylesheet_link_tag "application", :media => "screen, print" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mailings/_label.html.haml
%td{:class => cycle("label left", "label right")}
  .container
    - if contact.present? && contact.name.present?
      %p.name= contact.name
      %p.address
        = contact.address_1
        - if contact.address_2.present?
          %br/
          = contact.address_2
      %p== #{contact.city}, #{contact.state}
      %p.zipcode= contact.zipcode
      %p.country= contact.country

app/views/mailings/create.html.erb
<table id="labels">
  <% @contacts.in_groups_of(2).each do |contact1, contact2| %>
    <tr>
      <%= render :partial => "label", :locals => {:contact => contact1} %>
      <%= render :partial => "label", :locals => {:contact => contact2} %>
    </tr>
  <% end %>
</end>

app/views/mailings/new.html.erb
<h1>Mailing</h1>

<% form_tag(mailings_path(:format => "pdf"), :multipart => true) do %>
  <%= file_field_tag :payments %>
  <%= label_tag :skip, "Skip X first label slots" %><br/>
  <%= text_field_tag :skip, 0 %><br/>
  <%= submit_tag "Create labels!" %>
<% end -%>
<h1>Summary</h1>
<% form_tag(summary_mailings_path, :multipart => true) do %>
  <%= file_field_tag :payments %>
  <%= submit_tag "Show summary" %>
<% end -%>

app/views/mailings/summary.html.haml
- @contacts.each do |item_name, purchases|
  %table#summary
    %tr
      %th.item-title{:colspan => 4}= item_name
    %tr
      %th{:colspan => 2} Standard postage count
      %td{:colspan => 2}= purchases.select {|c| c.postage_price.zero? }.count
    %tr
      %th{:colspan => 2} Special postage count
      %td{:colspan => 2}= purchases.reject {|c| c.postage_price.zero? }.count
    %tr
      %th{:colspan => 2} TOTAL
      %td{:colspan => 2}= purchases.count
    %tr
      %th Name
      %th Value paid
      %th Postage
      %th Note
    - purchases.sort_by(&:value).reverse.each do |contact|
      %tr{:class => html_class_for(contact)}
        %td= contact.name
        %td= number_to_currency contact.value
        %td= number_to_currency contact.postage_price
        %td= contact.note